{% set name = "kerchunk" %}
{% set version = "0.2.9" %}
{% set python_min = "3.11" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/kerchunk-{{ version }}.tar.gz
  sha256: 86a54da9a57a94fd6fb97be786e2d83182d3d8e4fd7c0ea2b67cde3d0641df7d

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools_scm
    - setuptools
  run:
    - fsspec >=2025.2.0
    - python >={{ python_min }}
    - numcodecs
    - ujson
    - zarr >=3.0.1

test:
  imports:
    - kerchunk
  commands:
    - pip check
  requires:
    - pip
    - python >={{ python_min }}

about:
  home: https://github.com/fsspec/kerchunk
  summary: Functions to make reference descriptions for ReferenceFileSystem
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - valeriupredoi
    - martindurant
    - rsignell-usgs
