{% set name = "kerchunk" %}
{% set version = "0.2.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/kerchunk-{{ version }}.tar.gz
  sha256: 5e942719b14746e87923699fc04fee797e937eaddca503f6ff6564df2a6c3fb0

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - fsspec
    - python >=3.7
    - numcodecs <=0.11
    - ujson
    - zarr

test:
  imports:
    - kerchunk
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/fsspec/kerchunk
  summary: Functions to make reference descriptions for ReferenceFileSystem
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - valeriupredoi
    - martindurant
    - rsignell-usgs
